# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Marcel/Desktop/V4_5/Hardware/Synthese/Synthese.cache/wt [current_project]
set_property parent.project_path C:/Users/Marcel/Desktop/V4_5/Hardware/Synthese/Synthese.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Marcel/Desktop/V4_5/Hardware/Synthese/Synthese.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/Clocking_synth.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/DF_Serial_in_v1_0.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/DF_Wishbone_Interface.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/DF_Serial_out_v1_0.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/Serial_Wishbone_Interface.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/wb_arbiter.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/txt_util_pack_v1_2.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/mult.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/div.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/bsr2_processor_core.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Prozessor/bsr2_processor.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Speicher/intel_hex_pack.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Speicher/Memory.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/Timer.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/GPIO.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/Siebensegment_Anzeige.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/SSP.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/UART_Empfaenger.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/UART_Sender.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Peripherie/UART.vhd
  C:/Users/Marcel/Desktop/V4_5/Hardware/Beispielrechner_System.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Beispielrechner_System -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Beispielrechner_System.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Beispielrechner_System_utilization_synth.rpt -pb Beispielrechner_System_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
